#!/bin/bash
[A[Bcp -u *.html ..[D[D[D[D[D[D[D[D[C[C[C[C[C!./ ../[D[D[D[D[D[D[D[D[D[D[D[D[D[C[C[C[C[C[C[D[D[D[D[D[D[D[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D[D[C[C[C[C[C[C[C[B[D[D[D[D[D[D
